-- 1. Cria a tabela para armazenar perfis de usuário
CREATE TABLE public.profiles (
  id uuid NOT NULL,
  last_room character varying,
  CONSTRAINT profiles_pkey PRIMARY KEY (id),
  CONSTRAINT profiles_id_fkey FOREIGN KEY (id) REFERENCES auth.users(id) ON DELETE CASCADE
);

-- 2. Cria a tabela para armazenar as salas de jogo
CREATE TABLE public.rooms (
  id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  room_code character varying NOT NULL,
  creator_id uuid NOT NULL,
  game_started boolean DEFAULT false,
  CONSTRAINT rooms_pkey PRIMARY KEY (id),
  CONSTRAINT rooms_room_code_key UNIQUE (room_code),
  CONSTRAINT rooms_creator_id_fkey FOREIGN KEY (creator_id) REFERENCES auth.users(id) ON DELETE CASCADE
);

-- 3. Configura a função para criar um perfil automaticamente quando um novo usuário se cadastra
CREATE OR REPLACE FUNCTION public.handle_new_user()
RETURNS trigger
LANGUAGE plpgsql
SECURITY DEFINER SET search_path = public
AS $$
BEGIN
  INSERT INTO public.profiles (id)
  VALUES (new.id);
  RETURN new;
END;
$$;

-- 4. Cria o gatilho (trigger) que executa a função acima
CREATE TRIGGER on_auth_user_created
  AFTER INSERT ON auth.users
  FOR EACH ROW EXECUTE PROCEDURE public.handle_new_user();

-- 5. Habilita a Segurança em Nível de Linha (RLS) para as tabelas
ALTER TABLE public.profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.rooms ENABLE ROW LEVEL SECURITY;

-- 6. Cria as políticas de segurança para a tabela de perfis
-- Permite que usuários leiam e modifiquem apenas o seu próprio perfil.
CREATE POLICY "Users can view their own profile." ON public.profiles FOR SELECT USING (auth.uid() = id);
CREATE POLICY "Users can update own profile." ON public.profiles FOR UPDATE USING (auth.uid() = id) WITH CHECK (auth.uid() = id);

-- 7. Cria as políticas de segurança para a tabela de salas
-- Permite que qualquer usuário autenticado crie e veja as salas.
CREATE POLICY "Allow authenticated users to view rooms." ON public.rooms FOR SELECT USING (auth.role() = 'authenticated');
CREATE POLICY "Allow authenticated users to create rooms." ON public.rooms FOR INSERT WITH CHECK (auth.role() = 'authenticated');
-- Permite que apenas o criador (anfitrião) da sala a modifique ou exclua.
CREATE POLICY "Allow host to update own room." ON public.rooms FOR UPDATE USING (auth.uid() = creator_id) WITH CHECK (auth.uid() = creator_id);
CREATE POLICY "Allow host to delete own room." ON public.rooms FOR DELETE USING (auth.uid() = creator_id);
